# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# Number of virtualized CPUs
VM_CPU = ENV['VM_CPU'] || 4
#
# Amount of available RAM
VM_MEMORY = ENV['VM_MEMORY'] || 4096

IP_ADDRESS="10.2.2.2"

Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "centos/7"

  config.vm.provider "libvirt" do |v, override|
    v.memory = VM_MEMORY
    v.cpus   = VM_CPU
    v.driver = "kvm"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum -y install epel-release
    sudo yum -y install ansible
    sudo ansible-playbook -e ip_address=#{IP_ADDRESS} /home/vagrant/sync/playbook.yml
  SHELL

  config.vm.network "private_network", ip: "#{IP_ADDRESS}"
end
